apiVersion: instana.io/v1beta1
kind: InstanaAgent
metadata:
  name: instana-agent
  namespace: instana-agent
spec:
  agent.zone.name: ibm-us-east-api-connect
  agent.key: qUMhYJxjSv6uZh2SyqTEnw
  agent.endpoint.host: ec2-18-216-174-231.us-east-2.compute.amazonaws.com
  agent.endpoint.port: 1444
  agent.env:
    INSTANA_AGENT_TAGS: roks, api-c
  cluster.name: cpi4-apic-prod
  config.files:
    configuration.yaml: |
      com.instana.plugin.ibmdatapower:
        enabled: true
        poll_rate: 5
        instances:                   # Multiple DataPower instances can be specified
          production-gw-datapower-replica-0.cp4i-apic.svc.cluster.local:    # DataPower Host or IP address (required)
            port: '5554'              # The port of the DataPower REST Management Interface. (required)
            username: 'admin'       # The User ID that is used to connect to the DataPower. (required)
            password: '}33(vg^}u94yeyp8*fX|uRp1'   # The password of the User ID. (required) (stored in <APIC_cluster_name>-gw-admin secret)
            cluster: 'API-C Gateway'   # The cluster to group multiple DataPower instances. (optional)
          production-gw-datapower-replica-1.cp4i-apic.svc.cluster.local:    # DataPower Host or IP address (required)
            port: '5554'              # The port of the DataPower REST Management Interface. (required)
            username: 'admin'       # The User ID that is used to connect to the DataPower. (required)
            password: '}33(vg^}u94yeyp8*fX|uRp1'   # The password of the User ID. (required) (stored in <APIC_cluster_name>-gw-admin secret)
            cluster: 'API-C Gateway'   # The cluster to group multiple DataPower instances. (optional)  
          production-gw-datapower-replica-2.cp4i-apic.svc.cluster.local:    # DataPower Host or IP address (required)
            port: '5554'              # The port of the DataPower REST Management Interface. (required)
            username: 'admin'       # The User ID that is used to connect to the DataPower. (required)
            password: '}33(vg^}u94yeyp8*fX|uRp1'   # The password of the User ID. (required) (stored in <APIC_cluster_name>-gw-admin secret)
            cluster: 'API-C Gateway'   # The cluster to group multiple DataPower instances. (optional)|  
